Project_16HCB_View/Project_16HCB_View/Controllers/GlobalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project_16HCB_View.Controllers
{
    public class GlobalController : Controller
    {
        // GET: Global
        public PartialViewResult PartialViewMenu()
        {
            return PartialView();
        }

        public PartialViewResult PartialViewTrangChu()
        {
            if (TempData["login"] != null)
            {
                ViewBag.user = TempData["login"];
            }

            return PartialView();
        }

        public PartialViewResult PartialViewTinTuc()
        {
            return PartialView();
        }

        public PartialViewResult PartialViewChuongTrinhDaoTao()
        {
            return PartialView();
        }
    }
}

Project_16HCB_View/Project_16HCB_View/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="~/Scripts/css/w3.css" rel="stylesheet" />
<link href="~/Scripts/css/css.css" rel="stylesheet" />
<style>
    body, h1, h2, h3, h4, h5 {
        font-family: "Poppins", sans-serif
    }

    body {
        font-size: 16px;
    }

    .w3-half img {
        margin-bottom: -6px;
        margin-top: 16px;
        opacity: 0.8;
        cursor: pointer
    }

        .w3-half img:hover {
            opacity: 1
        }


    .dropdown-content {
        margin-left:92px;
        display: none;
        position: absolute;
        background-color: #f9f9f9;
        min-width: 160px;
        box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
        padding: 12px 16px;
        z-index: 1;
    }

    .dropdown:hover .dropdown-content {
        display: block;
    }
</style>
@RenderSection("css",false)
<body>

    <!-- Sidebar/menu -->
    <nav class="w3-sidebar w3-red w3-collapse w3-top w3-large w3-padding" style="z-index:3;width:300px;font-weight:bold;" id="mySidebar">
        <br>
        <a href="javascript:void(0)" onclick="w3_close()" class="w3-button w3-hide-large w3-display-topleft" style="width:100%;font-size:22px">Close Menu</a>
        <div class="w3-container">
            <h3 class="w3-padding-64"><b>KHOA HỌC TỰ NHIÊN</b></h3>
        </div>

        @Html.Action("PartialViewMenu", "Global")
    </nav>

    <!-- Top menu on small screens -->
    @*<header class="w3-container w3-top w3-hide-large w3-red w3-xlarge w3-padding">
            <a href="javascript:void(0)" class="w3-button w3-red w3-margin-right" onclick="w3_open()">☰</a>
            <span>Company Name</span>
        </header>*@

    <!-- Overlay effect when opening sidebar on small screens -->
    <div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

    <!-- !PAGE CONTENT! -->
    <div class="w3-main" style="margin-left:340px;margin-right:40px">

        <!-- End page content -->
        @RenderBody()
    </div>

    <!-- W3.CSS Container -->
    @*<div class="w3-light-grey w3-container w3-padding-32" style="margin-top:75px;padding-right:58px"><p class="w3-right">Powered by <a href="https://www.w3schools.com/w3css/default.asp" title="W3.CSS" target="_blank" class="w3-hover-opacity">w3.css</a></p></div>*@
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script>
        // Script to open and close sidebar
        function w3_open() {
            document.getElementById("mySidebar").style.display = "block";
            document.getElementById("myOverlay").style.display = "block";
        }

        function w3_close() {
            document.getElementById("mySidebar").style.display = "none";
            document.getElementById("myOverlay").style.display = "none";
        }

        // Modal Image Gallery
        function onClick(element) {
            document.getElementById("img01").src = element.src;
            document.getElementById("modal01").style.display = "block";
            var captionText = document.getElementById("caption");
            captionText.innerHTML = element.alt;
        }

        function getFormData(a) {
            for (var b = $(a + " input," + a + " select," + a + " textarea," + a + " checkboxchecked"), c = {}, d = 0; d < b.length; d++) {
                if ($(b[d]).attr('type') != 'checkbox')
                    c[b[d].name] = b[d].value;
                else {
                    c[b[d].name] = $(b[d]).prop('checked');
                }
            }
            return c
        }

    </script>
    @RenderSection("js", false)
</body>
</html>

Project_16HCB_View/Project_16HCB_View/Views/Shared/_LayoutTemp.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.3/themes/smoothness/jquery-ui.css">
    <!-- MetisMenu CSS -->
    <link href="/Scripts/vendor/metisMenu/metisMenu.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="/Scripts/dist/css/sb-admin-2.css" rel="stylesheet">
    <link href="~/Content/css/style-custom.css" rel="stylesheet" />
    <!-- Custom Fonts -->
    <link href="/Scripts/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.15/datatables.min.css" />
    <!-- DataTables CSS -->
    <link href="~/Scripts/vendor/datatables-plugins/dataTables.bootstrap.css" rel="stylesheet">

    <!-- DataTables Responsive CSS -->
    <link href="~/Scripts/vendor/datatables-responsive/dataTables.responsive.css" rel="stylesheet">
    <link href="~/Content/css/tablecss.css" rel="stylesheet" />
    <link href="~/Content/css/checkboxcustom.css" rel="stylesheet" />

    <link rel="stylesheet prefetch" href="http://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker.css">
    @RenderSection("heads", required: false)

</head>
<body>

    <div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/"></a>
            </div>
            <!-- /.navbar-header -->
            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li>
                            <a>Xin chào</a>
                        </li>

                        <li class="divider"></li>
                        <li>
                            <a href="~/doi-mat-khau"><i class="fa fa-user fa-fw"></i> Đổi mật khẩu</a>
                        </li>
                        <li>
                            <a id="btnLogout" style="cursor: pointer;"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->
            @RenderPage("_LeftMenu.cshtml")
            <!-- /.navbar-static-side -->
        </nav>
        <div id="page-wrapper">
            @RenderBody()
        </div>
        <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->
    <!-- Modal Logout -->
    <div class="modal fade" id="ModalLogout" role="dialog">
        <div class="modal-dialog" style="width:70%;">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Logout</h4>
                </div>

                <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
                <div class="modal-body">
                    Bạn có thật sự muốn được đăng xuất?
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" id="btnLogoutTrue" data-dismiss="modal">Đăng xuất</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
                </div>
            </div>
        </div>
    </div>
    <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>-->
    <script src="~/Scripts/vendor/jquery/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.3/jquery-ui.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="~/Scripts/Library/notify.js"></script>
    <!-- Metis Menu Plugin JavaScript -->
    <script src="/Scripts/vendor/metisMenu/metisMenu.min.js"></script>
    <!-- Custom Theme JavaScript -->
    <script src="/Scripts/dist/js/sb-admin-2.js"></script>
    <script src="~/Scripts/Library/jquery.twbsPagination.js"></script>
    <script src="~/Scripts/Library/jquery.blockUI.js"></script>
    <script src="~/Scripts/Library/jquery.form.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.15/datatables.min.js"></script>
    <script src="~/Scripts/vendor/datatables-plugins/dataTables.bootstrap.min.js"></script>
    <script src="~/Scripts/vendor/datatables-responsive/dataTables.responsive.js"></script>
    <script src="~/Scripts/vendor/datatables/js/jquery.dataTables.min.js"></script>

    <script src="http://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/bootstrap-datepicker.js"></script>

    <script type="text/javascript">
        function showLoading(btnID) {
            $("#" + btnID).button('loading');
            $.blockUI({ message: null });
        }

        function hideLoading(btnID) {
            $("#" + btnID).button('reset');
            $.unblockUI();
        }
    </script>
    @RenderSection("scripts", required: false)
</body>
</html>

Project_16HCB_View/Project_16HCB_View/Views/Shared/_LeftMenu.cshtml
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu"></ul>
    </div>
    <!-- /.sidebar-collapse -->
</div>