Project_16HCB_View/Project_16HCB_View/Controllers/GlobalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project_16HCB_View.Controllers
{
    public class GlobalController : Controller
    {
        // GET: Global
        public PartialViewResult PartialViewMenu()
        {
            return PartialView();
        }

        public PartialViewResult PartialViewTrangChu()
        {
            if (TempData["login"] != null)
            {
                ViewBag.user = TempData["login"];
            }

            return PartialView();
        }

        public PartialViewResult PartialViewTinTuc()
        {
            return PartialView();
        }

        public PartialViewResult PartialViewChuongTrinhDaoTao()
        {
            return PartialView();
        }
    }
}

Project_16HCB_View/Project_16HCB_View/Controllers/LoginController.cs
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Project_16HCB_View.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace Project_16HCB_View.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Login()
        {
           /* var hc = new HttpClient();
            hc.DefaultRequestHeaders.Accept.Clear();
            hc.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            string url = "http://localhost:1352/api/TaiKhoan/XemTaiKhoan/" + DataUserLogin.MaTaiKhoan;
            var res = hc.GetAsync(url).Result;

            if (res.StatusCode == System.Net.HttpStatusCode.OK)
            {
                var obj = res.Content.ReadAsAsync<TaiKhoan>().Result;

                MessageBox.Show("Tài khoản: " + obj.MATK + "\nHọ tên: " + obj.HOTEN + "\nSố dư: " + String.Format("{0:N0}", obj.SODUKHADUNG) + " VNĐ\nNgày hết hạn: " + obj.NGAYHETHAN.ToString("dd-MM-yyyy"));
            }*/
            return View();
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Login(string username, string password)
        {
            var hc = new HttpClient();
            hc.DefaultRequestHeaders.Accept.Clear();
            hc.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            string url = "http://localhost:52740/api/Login";
            
            if (password != null && password != "")
                password = Md5Hash(password);

            var res = hc.PostAsJsonAsync(url, new { username, password }).Result;

            if (res.StatusCode == System.Net.HttpStatusCode.OK)
            {
                var jobj = JObject.Parse(res.Content.ReadAsAsync<string>().Result);
                USER user = jobj["user"].ToObject<USER>();
                int sores = jobj["resPhieuDiem"].ToObject<int>();
                int soresSV = jobj["resTraPhieuDiemSV"].ToObject<int>();
                
                TempData["login"] = user;

                if (user != null)
                {
                    Session.Add("userid", user.C_userId);
                    Session.Add("loaiUS", user.C_loaiUS);                 
                    Session.Add("user", user);
                    Session.Add("resPhieuDiem", sores);
                    Session.Add("resTraPhieuDiemSV", soresSV);
                    return RedirectToAction("TrangChu", "TrangChu");
                }
            }
            else
            {
                var jObj = JObject.Parse(res.Content.ReadAsAsync<string>().Result);
                ViewBag.error = jObj["msg"].ToObject<string>();
            }

            return View();
        }

        // Mã hóa mật khẩu
        private string Md5Hash(string text)
        {
            MD5 md5 = new MD5CryptoServiceProvider();
            md5.ComputeHash(Encoding.ASCII.GetBytes(text));
            byte[] md5Bytes = md5.Hash;
            StringBuilder sb = new StringBuilder();

            foreach (byte b in md5Bytes)
            {
                sb.Append(b.ToString("x2"));
            }

            return sb.ToString();
        }
    }
}

Project_16HCB_View/Project_16HCB_View/Controllers/MonHocController.cs
using Newtonsoft.Json.Linq;
using Project_16HCB_View.Models;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web.Mvc;
using System.Linq;

namespace Project_16HCB_View.Controllers
{
    public class MonHocController : Controller
    {
        // GET: MonHoc
        [HttpGet]
        public ActionResult Index()
        {
            var hc = new HttpClient();
            hc.DefaultRequestHeaders.Accept.Clear();
            hc.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            string url = "http://localhost:52740/api/MonHoc";
            var resp = hc.GetAsync(url).Result;
            var jObj = JObject.Parse(resp.Content.ReadAsAsync<string>().Result);

            if (resp.StatusCode != System.Net.HttpStatusCode.OK)
            {
                ViewBag.errorMsg = jObj["msg"].ToObject<string>();
            }
            else
            {
                var lstMonHoc = jObj["lst"].ToObject<List<MonHoc>>();
                ViewBag.lstMonHoc = lstMonHoc;
            }

            return View();
        }

        [HttpPost]
        public ActionResult Search(string tenMH)
        {
            var hc = new HttpClient();
            hc.DefaultRequestHeaders.Accept.Clear();
            hc.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            string url = "http://localhost:52740/api/MonHoc";
            var resp = hc.GetAsync(url).Result;
            var jObj = JObject.Parse(resp.Content.ReadAsAsync<string>().Result);

            if (resp.StatusCode != System.Net.HttpStatusCode.OK)
            {
                ViewBag.errorMsg = jObj["msg"].ToObject<string>();
            }
            else
            {
                var lstMonHoc = jObj["lst"].ToObject<List<MonHoc>>();
                ViewBag.lstMonHoc = lstMonHoc.Where(n => n.C_tenMH.ToLower().Contains(tenMH.ToLower())).ToList();
            }

            return View("Index");
        }
    }
}

Project_16HCB_View/Project_16HCB_View/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project_16HCB_View.Controllers
{
    public class ReportController : Controller
    {
        // GET: Report
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ReportStudent() {
            return View();
        }

        public ActionResult ReportDanhSachHocSinhNghi()
        {
            return View();
        }
    }
}

Project_16HCB_View/Project_16HCB_View/Controllers/SendMailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project_16HCB_View.Controllers
{
    public class SendMailController : Controller
    {
        // GET: SendMail
        public ActionResult SendMail()
        {

            if (Session["userid"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Login");
            }
           
        }
    }
}

Project_16HCB_View/Project_16HCB_View/Views/Global/PartialViewChuongTrinhDaoTao.cshtml
<div class="w3-container" id="contact" style="margin-top:75px">
    <h1 class="w3-xxxlarge w3-text-red"><b>Đào Tạo</b></h1>
    <hr style="width:50px;border:5px solid red" class="w3-round">
    <p>The best team in the world.</p>
    <p>
        We are lorem ipsum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure
        dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor
        incididunt ut labore et quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
    </p>
    <p><b>Our designers are thoughtfully chosen</b>:</p>
</div>

Project_16HCB_View/Project_16HCB_View/Views/Global/PartialViewMenu.cshtml
@using Project_16HCB_View.Utilities;
<div class="w3-bar-block">
    <div href="#" onclick="window.location.href = '#'; w3_close()" class="w3-bar-item w3-button w3-hover-white">Trang Chủ</div>
    <div href="#designers" onclick="window.location.href = '#designers'; w3_close()" class="w3-bar-item w3-button w3-hover-white">Tin Tức</div>
    <div href="#student" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white dropdown">
        Sinh Viên
        
        <div class="dropdown-content">
            @if ((int)SessionProvider.GetUserTypeFromSession() == 2)
    {
        <div>
            @Html.ActionLink("Gửi mail", "SendMail", "SendMail", null, new { style = "text-decoration: none;" })
        </div>

}
            @if ((int)SessionProvider.GetUserTypeFromSession() == 1)
    {
        <div>
            @Html.ActionLink("Thời Khóa Biểu", "ThoiKhoabieu", "ThoiKhoabieu", null, new { style = "text-decoration: none;" })
        </div>
        <hr />
        <div>
            @Html.ActionLink("Thông Tin Điểm Danh", "Infodiemdanh", "Student", null, new { style = "text-decoration: none;" })
        </div>
        <hr />
        <div>
            @Html.ActionLink("Danh sách môn học", "Index", "MonHoc", null, new { style = "text-decoration: none;" })
        </div>
        <hr />
        <div>
            @Html.ActionLink("Tạo Phiếu Điểm", "TaoPhieuDiem", "PhieuDiem", null, new { style = "text-decoration: none;" })
        </div>
        <hr />
        <div>
            @Html.ActionLink("Nhận Phiếu Điểm (" + SessionProvider.GetSoLuongResTraPhieuDiemFromSession() + ")", "NhanPhieuDiem", "PhieuDiem", null, new { style = "text-decoration: none;" })
        </div>
}

        </div>
       

    </div>

    <div href="#teacher" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white dropdown">
        Giáo Viên

        @if ((int)SessionProvider.GetUserTypeFromSession() == 2)
        {
            <div class="dropdown-content">
                <div>
                    @Html.ActionLink("Gửi mail", "SendMail", "SendMail", null, new { style = "text-decoration: none;" })
                </div>
                <hr>
                <div>
                    @Html.ActionLink("Thông Tin Phiếu Điểm (" + SessionProvider.GetSoLuongResPhieuDiemFromSession() + ")", "DanhSachPhieuDiem", "PhieuDiem", null, new { style = "text-decoration: none", id = "sores" })
                </div>
                <hr />
                <div>
                    @Html.ActionLink("Thống kê số lượng nghỉ", "ReportStudent", "Report", null, new { style = "text-decoration: none;" })
                </div>
            </div>

        }




    </div>
    <div href="#contact" onclick="window.location.href = '#contact'; w3_close()" class="w3-bar-item w3-button w3-hover-white">Chương Trình Đào Tạo</div>
    <div href="#login" class="w3-bar-item w3-button w3-hover-white">
        @Html.ActionLink("Đăng nhập", "Login", "Login", null, new { style = "text-decoration: none;" })
    </div>
</div>

Project_16HCB_View/Project_16HCB_View/Views/Global/PartialViewTinTuc.cshtml
<div class="w3-container" id="designers" style="margin-top:75px">
    <h1 class="w3-xxxlarge w3-text-red"><b>Tin Tức</b></h1>
    <hr style="width:50px;border:5px solid red" class="w3-round">
    <p>We are a interior design service that focus on what's best for your home and what's best for you!</p>
    <p>
        Some text about our services - what we do and what we offer. We are lorem ipsum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure
        dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor
        incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
    </p>
</div>

Project_16HCB_View/Project_16HCB_View/Views/Global/PartialViewTrangChu.cshtml
@model Project_16HCB_View.Models.USER

@if (ViewBag.user != null)
{
    <div class="w3-panel w3-red">
        <div class="w3-right-align"><p><a href="#">@ViewBag.user.C_username</a></p></div>
    </div>
}

<div class="w3-container" style="margin-top:80px" id="showcase">
    <h1 class="w3-xxxlarge w3-text-red"><b>Trang Chủ</b></h1>
    <hr style="width:50px;border:5px solid red" class="w3-round">
</div>

<!-- Photo grid (modal) -->
<div class="w3-row-padding">
    Trang chủ
</div>